language: minimal
install: true

jdk:
  - openjdk11

git:
  depth: 3
  quiet: true

stages:
  - build
  - name: CI_ops
    if: branch = dmz && type = push

.gradle_template: &gradle
  language: java
  before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/

jobs:
  include:
    - <<: *gradle
      stage: build
      before_script:
        - chmod +x ./gradlew
      script:
        - ./gradlew build --scan -s
    - stage: CI_ops
      script:
        - git remote add master_uplink ssh://git@github.com/$TRAVIS_REPO_SLUG.git
        - git push master_uplink dmz:master
        - git remote remove master_uplink
