/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CBatL;

import CBatL.view.graphicalview.views.BShipPanel;
import CBatL.view.graphicalview.controllers.QuitController;
import CBatL.view.graphicalview.controllers.ResetController;
import CBatL.view.graphicalview.controllers.ChangeViewController;
import CBatL.view.graphicalview.views.BattleShip;
import CBatL.view.graphicalview.views.HelpView;

import javax.swing.*;

/**
 * Coucou
 */
public class App {
  public static void main(String[] args)
  {
    System.out.println(new App().getGreeting());
    new BattleShip();
  }

  public String getGreeting() {
    return "Hello world.";
  }
}
