/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CBatL;

import CBatL.view.graphicalview.views.GraphicalView;

/**
 * Coucou
 */
public class App {
  public static void main(String[] args)
  {
    System.out.println(new App().getGreeting());
    new GraphicalView();
  }

  public String getGreeting() {
    return "Hello world.";
  }
}
